### ISSUE TITLE
TEXTURE CONVERTOR - png to wiiu error

### ISSUE THREAD

**Issue by Erich112** [WodsonKun/JustDanceTools#9]
How're you doing?
Welcome to WodsonKun's TextureConverter!
Select a option:
-----------------------------
[1] Convert textures to PC format
[2] Convert textures to Wii format
[3] Convert textures to Wii U format
[4] Convert textures to Xbox 360 format
[5] Convert textures to PlayStation 3 format
[6] Convert textures to Nintendo Switch format
[7] Exits the TextureConverter
-----------------------------
Choose your option: 3
Traceback (most recent call last):
  File "C:\Users\Erich21\Downloads\JustDanceTools-main\[TEXT] TextureConverter\textureconverter.py", line 33, in <module>
    Platform.text2ubi('wiiu')
  File "C:\Users\Erich21\Downloads\JustDanceTools-main\[TEXT] TextureConverter\bin\libs\ubiart.py", line 31, in text2ubi
    Tools.texture2dds(PNGTexture)
  File "C:\Users\Erich21\Downloads\JustDanceTools-main\[TEXT] TextureConverter\bin\libs\texture.py", line 51, in texture2dds
    subprocess.check_call('quicktex encode bc3 --no-flip input//' + texture + ' -o temp//', stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\Erich21\Downloads\JustDanceTools-main\[TEXT] TextureConverter>

I installed the libraries in the "requirements.txt" file too

**Comment by WodsonKun** [comment]
Are you sure?
The log says it's missing the `quicktex` module

**Comment by Erich112** [comment]
this is what i get if i do "pip install quicktex" in cmd

Requirement already satisfied: quicktex in c:\users\erich21\appdata\roaming\python\python311\site-packages (0.2.0)
Requirement already satisfied: Pillow in c:\users\erich21\appdata\roaming\python\python311\site-packages (from quicktex) (10.2.0)
Requirement already satisfied: click in c:\users\erich21\appdata\roaming\python\python311\site-packages (from quicktex) (8.1.7)
Requirement already satisfied: colorama in c:\users\erich21\appdata\roaming\python\python311\site-packages (from click->quicktex) (0.4.6)

**Comment by alexo310** [comment]
install the binary version and put it in the same path as the script.

**Comment by WodsonKun** [comment]
Do you have more than one version of Python installed?

**Comment by alexo310** [comment]
wait can you rename the textureconverter folder and remove the space?

**Comment by WodsonKun** [comment]
> wait can you rename the textureconverter folder and remove the space?



@alexo310 the space shouldn't be a problem, as quicktex is a python module
but having two python versions installed simultaneously can be, as pip can install quicktex in the wrong ver
